import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, extname } from 'node:path';
const root = join(dirname(fileURLToPath(import.meta.url)), '.');
const MIME = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.glb':'model/gltf-binary' };
const srv = await new Promise(r=>{ const s=createServer((q,s)=>{ let p=q.url.split('?')[0]; if(p==='/')p='/index.html'; try{ statSync(join(root,p)); s.writeHead(200,{'Content-Type':MIME[extname(p)]||'application/octet-stream'}); s.end(readFileSync(join(root,p))); }catch{ s.writeHead(404); s.end('x'); } }); s.listen(0,'127.0.0.1',()=>r(s)); });
const port=srv.address().port;
const b=await chromium.launch(); const pg=await b.newPage();
const errs=[]; pg.on('pageerror',e=>errs.push('PE:'+e.message));
pg.on('console',m=>{const t=m.type(); if(t==='error'||t==='warning')errs.push(t[0]+':'+m.text());});
await pg.addInitScript(()=>{ window.__rej=[];window.__initLog=[]; window.addEventListener('unhandledrejection',e=>{ window.__rej.push((e.reason&&e.reason.stack)||String(e.reason)); }); });
await pg.goto('http://127.0.0.1:'+port+'/',{waitUntil:'networkidle'});
await pg.waitForTimeout(400);
await pg.evaluate(()=>document.getElementById('playBtn').click());
await new Promise(r=>setTimeout(r,6000));
const r = await pg.evaluate(()=>{ const g=window.game; return { state:g.state, enemies:g.enemies?g.enemies.length:0, enemy0Mesh:g.enemies&&g.enemies[0]?!!g.enemies[0].mesh:false, rej:window.__rej, initLog:window.__initLog }; });
console.log('PROBE:', JSON.stringify(r,null,2));
console.log('ERRORS:', errs.slice(0,8).join(' | ')||'none');
await b.close(); srv.close();
